# Generated by Django 4.2.4 on 2023-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='time',
            name='end_date',
            field=models.DateField(verbose_name='Окончание времени процедуры'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_date',
            field=models.DateField(verbose_name='Начало времени процедуры'),
        ),
    ]
