# Generated by Django 4.2.4 on 2023-08-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_alter_shedule_options_alter_time_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end_date',
            field=models.DateTimeField(verbose_name='Окончание времени процедуры'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_date',
            field=models.DateTimeField(verbose_name='Начало времени процедуры'),
        ),
    ]
