# Generated by Django 4.2.4 on 2023-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_alter_time_end_date_alter_time_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['shedule', 'user'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AddField(
            model_name='time',
            name='status',
            field=models.CharField(blank=True, max_length=5, verbose_name='Статус записи'),
        ),
    ]
