# Generated by Django 4.2.4 on 2023-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_alter_booking_options_time_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='status',
        ),
        migrations.AddField(
            model_name='shedule',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус расписания'),
        ),
    ]
